---
title: "Haoyuan"
author: "Haoyuan"
date: "11/18/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages('tidyverse')
# install.packages('ggcorrplot')
# install.packages('clustertend')
# install.packages('gridExtra')
# install.packages('ggplot2')
# # install.packages('arules')
# # install.packages('arulesViz')


# import library
library(tidyverse)
library(ggcorrplot)
library(clustertend)
library(gridExtra)
library(ggplot2)
# library(arules)
# library(arulesViz)

# summary function
# for numeric attributes
summarize_numeric = function(dataset) {
    dataset = select_if(dataset, is.numeric)
    summary.table = data.frame(Attribue = names(dataset))
    summary.table = summary.table %>% 
        mutate('Missing Values' = apply(dataset, 2, function(x) sum(is.na(x))),
               'Unique Values' = apply(dataset, 2, function(x) length(unique(x))),
               'Mean' = round(colMeans(dataset, na.rm = TRUE),2),
               'Min' = apply(dataset, 2, function(x) min(x, na.rm = TRUE)),
               'Max' = apply(dataset, 2, function(x) max(x, na.rm = TRUE)),
               'SD' = round(apply(dataset, 2, function(x) sd(x, na.rm = TRUE)),2))
    summary.table
    }

# for character attributes
summarize_character = function(dataset) {
    dataset = select_if(dataset, is.character)
    summary.table = data.frame(Attribue = names(dataset))
    summary.table = summary.table %>% 
        mutate('Missing Values' = apply(dataset, 2, function(x) sum(is.na(x))),
               'Unique Values' = apply(dataset, 2, function(x) length(unique(x))))
    summary.table
}

# winsorize

winsorize = function(data, end){
  endpoint = quantile(data, probs=c(end, 1-end), na.rm = T)
  data[data < endpoint[1]] = endpoint[1]
  data[data > endpoint[2]] = endpoint[2]
  return(data)
}

```

# DATA PROCESSING

```{r}
#Libraries
library(readr)
library(dplyr)

#Dataset
diabetic_data <- read_csv("diabetes+130-us+hospitals+for+years+1999-2008/diabetic_data.csv")
IDS_mapping <- read_csv("diabetes+130-us+hospitals+for+years+1999-2008/IDS_mapping.csv")

#Reform IDS Mapping
##Split the IDS Mapping
split_indices <- c(0, which(is.na(IDS_mapping$admission_type_id)), nrow(IDS_mapping) + 1)
split_data <- lapply(seq_along(split_indices[-1]), function(i) {
  start_index <- split_indices[i] + 1
  end_index <- split_indices[i + 1] - 1
  IDS_mapping[start_index:end_index, , drop = FALSE]
})
split_data <- lapply(split_data, as.data.frame)
rm(split_indices)

##Remove the first row because it was the column name
for (i in seq_along(split_data)[-1]) {
  colnames(split_data[[i]])[1] <- split_data[[i]][1, 1]
  split_data[[i]] <- dplyr::slice(split_data[[i]], -1)
}
rm(i)
##Make the first column a numeric type
split_data <- lapply(split_data, function(df) {
  df[[1]] <- as.numeric(df[[1]])
  return(df)
})

##Split the list into separate dataframes
names(split_data) <- c("admission_type_id", "discharge_disposition_id", "admission_source_id")
list2env(split_data, envir = .GlobalEnv)

##Remove Redundant Data
rm(split_data)
rm(IDS_mapping)

#Reform Diabetic Data 
##Replace "?" values to NA
diabetic_data[diabetic_data == "?"] <- NA

diabetic_data
```


```{r}
# import data file
file_path = "/Users/traviszhang/Documents/STUDY/TASI-DS/Dec Competition/DataScience-Diabetes/diabetes+130-us+hospitals+for+years+1999-2008/diabetic_data.csv"
df = read_csv(file_path)
df

# initial data review
class(diabetic_data)
str(diabetic_data)
names(diabetic_data)
summarize_numeric(diabetic_data)
summarize_character(diabetic_data)

```
```{r}
# other data processing



```




```{r}
#People
g1 = ggplot(df) + geom_histogram(aes(x = Income), bins = 500)
g2 = ggplot(df) + geom_histogram(aes(x = Kidhome), bins = 3)
g3 = ggplot(df) + geom_histogram(aes(x = Teenhome), bins = 3)
g4 = ggplot(df) + geom_histogram(aes(x = Recency), bins = 50)
g18 = ggplot(df) + geom_histogram(aes(x = Age), bins = 5)
g21 = ggplot(df) + geom_histogram(aes(x = Seniority),bins = 50)



```