---
title: "Integration"
author: "Meynard & Haoyuan"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(dplyr)
library(ggcorrplot)
library(tibble)
library(ggplot2)
library(tidyr)
library(stringr)
library(stats)
library(nnet)
library(tidyverse)
library(corrplot)
```

# Setting Environment

```{r dataset, echo=FALSE}
source(file = "Clean Data.R")
```

# Summary
```{r}
# summary function
# for numeric attributes
summarize_numeric = function(dataset) {
    dataset = select_if(dataset, is.numeric)
    summary.table = data.frame(Attribue = names(dataset))
    summary.table = summary.table %>% 
        mutate('Missing Values' = apply(dataset, 2, function(x) sum(is.na(x))),
               'Missing Values Percentage' = round(sapply(dataset, function(x) sum(is.na(x)) / length(x) * 100),2),
               'Unique Values' = apply(dataset, 2, function(x) length(unique(x))),
               'Mean' = round(colMeans(dataset, na.rm = TRUE),2),
               'Min' = apply(dataset, 2, function(x) min(x, na.rm = TRUE)),
               'Max' = apply(dataset, 2, function(x) max(x, na.rm = TRUE)),
               'SD' = round(apply(dataset, 2, function(x) sd(x, na.rm = TRUE)),2))
    summary.table
    }

# for character attributes
summarize_character = function(dataset) {
    dataset = select_if(dataset, is.character)
    summary.table = data.frame(Attribue = names(dataset))
    summary.table = summary.table %>% 
        mutate('Missing Values' = apply(dataset, 2, function(x) sum(is.na(x))),
               'Missing Values Percentage' = round(sapply(dataset, function(x) sum(is.na(x)) / length(x) * 100),2),
               'Unique Values' = apply(dataset, 2, function(x) length(unique(x))))
    summary.table
}

# winsorize
winsorize = function(data, end){
  endpoint = quantile(data, probs=c(end, 1-end), na.rm = T)
  data[data < endpoint[1]] = endpoint[1]
  data[data > endpoint[2]] = endpoint[2]
  return(data)
}
```

```{r}

diabetic_data

# summary
diabetic_data$diag_1 <- as.character(diabetic_data$diag_1)
diabetic_data$diag_2 <- as.character(diabetic_data$diag_2)
diabetic_data$diag_3 <- as.character(diabetic_data$diag_3)
#diabetic_data$readmitted_num <- as.numeric(diabetic_data$readmitted_num)

summarize_numeric(diabetic_data)
summarize_character(diabetic_data)

#diabetic_data$diag_1 <- as.numeric(diabetic_data$diag_1)
#diabetic_data$diag_2 <- as.numeric(diabetic_data$diag_2)
#diabetic_data$diag_3 <- as.numeric(diabetic_data$diag_3)

```
```{r}
# remove cols
# df$citoglipton == df$examide #there are the same, drop one
df = select(diabetic_data, -encounter_id, -weight, -payer_code, -medical_specialty, -citoglipton)

# drop missing value
df = na.omit(df)
df = df %>% filter(df$gender != 'Unknown/Invalid')

df
summarize_numeric(df)
summarize_character(df)

```

```{r}
# Feature Engineering

# service_utilization
# df$service_utilization <- df$number_outpatient + df$number_emergency + df$number_inpatient

# num_drug_change

keys <- c('metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'insulin', 'glyburide-metformin', 'tolazamide', 'metformin-pioglitazone', 'metformin-rosiglitazone', 'glimepiride-pioglitazone', 'glipizide-metformin', 'troglitazone', 'tolbutamide', 'acetohexamide', 'examide')

for (col in keys) {
  colname <- paste0(col, 'temp')
  df[[colname]] <- ifelse(df[[col]] %in% c('No', 'Steady'), 0, 1)
}
                
df$numchange <- 0

for (col in keys) {
  colname <- paste0(col, 'temp')
  df$numchange <- df$numchange + df[[colname]]
  df[[colname]] <- NULL
}

#df = df[, -which(names(df) %in% keys)]

# medication change
df$change <- ifelse(df$change == 'Ch', 1, 0)

# gender
df$gender <- ifelse(df$gender == 'Male', 1, 0)

# diabetesMed
df$diabetesMed <- ifelse(df$diabetesMed == 'Yes', 1, 0)

# medication
for (col in keys) {
  df[[col]] <- ifelse(df[[col]] %in% c('No', 'Steady', 'Up', 'Down'), 1, 0)
}

# A1Cresult
df$A1Cresult <- ifelse(df$A1Cresult %in% c('>7', '>8'), 1,
                ifelse(df$A1Cresult == 'Norm', 0,
                ifelse(df$A1Cresult == 'None', 0, df$A1Cresult)))
df$A1Cresult = as.numeric(df$A1Cresult)
#max_glu_serum
df$max_glu_serum <- ifelse(df$max_glu_serum %in% c('>200', '>300'), 1,
                    ifelse(df$max_glu_serum == 'Norm', 0,
                    ifelse(df$max_glu_serum == 'None', -99, df$max_glu_serum)))
df$max_glu_serum = as.numeric(df$max_glu_serum)
# age
# df <- df %>%
# mutate(age_temp = ifelse(age == "[0-10)", 1,
#              ifelse(age == "[10-20)", 2,
#              ifelse(age == "[20-30)", 3,
#              ifelse(age == "[30-40)", 4,
#              ifelse(age == "[40-50)", 5,
#              ifelse(age == "[50-60)", 6,
#              ifelse(age == "[60-70)", 7,
#              ifelse(age == "[70-80)", 8,
#              ifelse(age == "[80-90)", 9,
#              ifelse(age == "[90-100)", 10, NA
#              )))))))))))

# duplicates (keep first)
# df <- df %>%
#   distinct(patient_nbr, .keep_all = TRUE, .keep_last = FALSE)

# readmitted
df = df %>%
  mutate(readmitted_num = ifelse(readmitted == "NO", 0, ifelse(readmitted %in% c("<30", ">30"), 1, readmitted)))
df$readmitted_num = as.numeric(df$readmitted_num)

# DRG
# df <- df %>%
# mutate(DRG_1_temp = ifelse(DRG_1 =='Metabolism and Immunity', 1,
#                     ifelse(DRG_1 =='Circulatory System', 2,
#                     ifelse(DRG_1 =='Diabetes Mellitus', 3,
#                     ifelse(DRG_1 =='Ill-Defined Conditions', 4,
#                     ifelse(DRG_1 =='Complications of Pregnancy, Childbirth, and the Puerperium', 5,
#                     ifelse(DRG_1 =='Injury and Poisoning', 6,
#                     ifelse(DRG_1 =='Respiratory System', 7,
#                     ifelse(DRG_1 =='Infectious and Parasitic', 8,
#                     ifelse(DRG_1 =='Digestive System', 9,
#                     ifelse(DRG_1 =='Mental Disorders', 10,
#                     ifelse(DRG_1 =='Genitourinary System', 11,
#                     ifelse(DRG_1 =='Neoplasms', 12,
#                     ifelse(DRG_1 =='Musculoskeletal and Connective Tissue', 13,
#                     ifelse(DRG_1 =='Skin and Subcutaneous Tissue', 14,
#                     ifelse(DRG_1 =='Nervous System and Sense Organ', 15,
#                     ifelse(DRG_1 =='Blood and Blood forming Organs', 16,
#                     ifelse(DRG_1 =='Congenital Anomalies', 17, NA
#              ))))))))))))))))))

# df <- df %>%
# mutate(DRG_2_temp = ifelse(DRG_2 =='Metabolism and Immunity', 1,
#                     ifelse(DRG_2 =='Circulatory System', 2,
#                     ifelse(DRG_2 =='Diabetes Mellitus', 3,
#                     ifelse(DRG_2 =='Ill-Defined Conditions', 4,
#                     ifelse(DRG_2 =='Complications of Pregnancy, Childbirth, and the Puerperium', 5,
#                     ifelse(DRG_2 =='Injury and Poisoning', 6,
#                     ifelse(DRG_2 =='Respiratory System', 7,
#                     ifelse(DRG_2 =='Infectious and Parasitic', 8,
#                     ifelse(DRG_2 =='Digestive System', 9,
#                     ifelse(DRG_2 =='Mental Disorders', 10,
#                     ifelse(DRG_2 =='Genitourinary System', 11,
#                     ifelse(DRG_2 =='Neoplasms', 12,
#                     ifelse(DRG_2 =='Musculoskeletal and Connective Tissue', 13,
#                     ifelse(DRG_2 =='Skin and Subcutaneous Tissue', 14,
#                     ifelse(DRG_2 =='Nervous System and Sense Organ', 15,
#                     ifelse(DRG_2 =='Blood and Blood forming Organs', 16,
#                     ifelse(DRG_2 =='Congenital Anomalies', 17, NA
#              ))))))))))))))))))

# df <- df %>%
# mutate(DRG_3_temp = ifelse(DRG_3 =='Metabolism and Immunity', 1,
#                     ifelse(DRG_3 =='Circulatory System', 2,
#                     ifelse(DRG_3 =='Diabetes Mellitus', 3,
#                     ifelse(DRG_3 =='Ill-Defined Conditions', 4,
#                     ifelse(DRG_3 =='Complications of Pregnancy, Childbirth, and the Puerperium', 5,
#                     ifelse(DRG_3 =='Injury and Poisoning', 6,
#                     ifelse(DRG_3 =='Respiratory System', 7,
#                     ifelse(DRG_3 =='Infectious and Parasitic', 8,
#                     ifelse(DRG_3 =='Digestive System', 9,
#                     ifelse(DRG_3 =='Mental Disorders', 10,
#                     ifelse(DRG_3 =='Genitourinary System', 11,
#                     ifelse(DRG_3 =='Neoplasms', 12,
#                     ifelse(DRG_3 =='Musculoskeletal and Connective Tissue', 13,
#                     ifelse(DRG_3 =='Skin and Subcutaneous Tissue', 14,
#                     ifelse(DRG_3 =='Nervous System and Sense Organ', 15,
#                     ifelse(DRG_3 =='Blood and Blood forming Organs', 16,
#                     ifelse(DRG_3 =='Congenital Anomalies', 17, NA
#              ))))))))))))))))))


df
summarize_numeric(df)
summarize_character(df)

```
```{r}
##unique(df$DRG_1)

# model <- glm(readmitted_num ~ 
#                age + 
#                gender +
#                time_in_hospital +
#                num_lab_procedures +
#                num_procedures +
#                num_medications +
#                number_outpatient +
#                number_emergency +
#                number_inpatient +
#                number_diagnoses +
#                # service_utilization +
#                numchange +
#                DRG_1_temp +
#                # DRG_2_temp +
#                # DRG_3_temp +
#                change +
#                diabetesMed +
#                numchange +
#                max_glu_serum +
#                A1Cresult
#                
#              , data = df, family = "binomial")

# Summary of the logistic regression model
# summary(model)
```

```{r}
# race
df$Caucasian = ifelse(df$race =='Caucasian', 1, 0)
df$AfricanAmerican = ifelse(df$race =='AfricanAmerican', 1, 0)
df$Asian = ifelse(df$race =='Asian', 1, 0)
df$Hispanic = ifelse(df$race =='Hispanic', 1, 0)
df$Other = ifelse(df$race =='Other', 1, 0)

#Age group
df$age_group_1 = ifelse(df$age == '[0-10)', 1, 0)
df$age_group_2 = ifelse(df$age == '[10-20)', 1, 0)
df$age_group_3 = ifelse(df$age == '[20-30)', 1, 0)
df$age_group_4 = ifelse(df$age == '[30-40)', 1, 0)
df$age_group_5 = ifelse(df$age == '[40-50)', 1, 0)
df$age_group_6 = ifelse(df$age == '[50-60)', 1, 0)
df$age_group_7 = ifelse(df$age == '[60-70)', 1, 0)
df$age_group_8 = ifelse(df$age == '[70-80)', 1, 0)
df$age_group_9 = ifelse(df$age == '[80-90)', 1, 0)
df$age_group_10 = ifelse(df$age == '[90-100)', 1, 0)

#age_group_1 '[0-10)'
#age_group_2 '[10-20)'
#age_group_3 '[20-30)'
#age_group_4 '[30-40)'
#age_group_5 '[40-50)'
#age_group_6 '[50-60)'
#age_group_7 '[60-70)'
#age_group_8 '[70-80)'
#age_group_9 '[80-90)'
#age_group_10 '[90-100)'



#DRG code  
df$DRG_code_1 = ifelse(df$DRG_1 == 'Metabolism and Immunity', 1, 0)
df$DRG_code_2 = ifelse(df$DRG_1 == 'Circulatory System', 1, 0)
df$DRG_code_3 = ifelse(df$DRG_1 == 'Diabetes Mellitus', 1, 0)
df$DRG_code_4 = ifelse(df$DRG_1 == 'Ill-Defined Conditions', 1, 0)
df$DRG_code_5 = ifelse(df$DRG_1 == 'Complications of Pregnancy, Childbirth, and the Puerperium', 1, 0)
df$DRG_code_6 = ifelse(df$DRG_1 == 'Injury and Poisoning', 1, 0)
df$DRG_code_7 = ifelse(df$DRG_1 == 'Respiratory System', 1, 0)
df$DRG_code_8 = ifelse(df$DRG_1 == 'Infectious and Parasitic', 1, 0)
df$DRG_code_9 = ifelse(df$DRG_1 == 'Digestive System', 1, 0)
df$DRG_code_10 = ifelse(df$DRG_1 == 'Mental Disorders', 1, 0)
df$DRG_code_11 = ifelse(df$DRG_1 == 'Genitourinary System', 1, 0)
df$DRG_code_12 = ifelse(df$DRG_1 == 'Neoplasms', 1, 0)
df$DRG_code_13 = ifelse(df$DRG_1 == 'Musculoskeletal and Connective Tissue', 1, 0)
df$DRG_code_14 = ifelse(df$DRG_1 == 'Skin and Subcutaneous Tissue', 1, 0)
df$DRG_code_15 = ifelse(df$DRG_1 == 'Nervous System and Sense Organ', 1, 0)
df$DRG_code_16 = ifelse(df$DRG_1 == 'Blood and Blood forming Organs', 1, 0)
df$DRG_code_17 = ifelse(df$DRG_1 == 'Congenital Anomalies', 1, 0)



df

```
```{r}
##unique(df$DRG_1)

model <- glm(readmitted_num ~ 
              age_group_1 +
              age_group_2 +
              age_group_3 +
              age_group_4 +
              age_group_5 +
              age_group_6 +
              age_group_7 +
              age_group_8 +
              age_group_9 +
              # age_group_10 +
# DRG_code_1 +
DRG_code_2 +
DRG_code_3 +
DRG_code_4 +
DRG_code_5 +
DRG_code_6 +
DRG_code_7 +
DRG_code_8 +
DRG_code_9 +
DRG_code_10 +
DRG_code_11 +
DRG_code_12 +
DRG_code_13 +
DRG_code_14 +
DRG_code_15 +
DRG_code_16 +
DRG_code_17 +

               gender +
  Caucasian +
  AfricanAmerican +
  Asian +
  Hispanic +
# Other +
               time_in_hospital +
               # num_lab_procedures +
               # num_procedures +
               # num_medications +
               number_outpatient +
               number_emergency +
               number_inpatient +
               number_diagnoses +
               # service_utilization +
               # numchange +
               # DRG_1_temp +
               # DRG_2_temp +
               # DRG_3_temp +
               # change +
               diabetesMed +
               #numchange +
               max_glu_serum +
               A1Cresult
               
             , data = df, family = "binomial")

# Summary of the logistic regression model
summary(model)
```





```{r}
unique(df$DRG_1)
```
















```{r}

# group_by(diabetic_data$encounter_id)

result <- diabetic_data %>%
  group_by(A1Cresult) %>%
  summarize(count = n()) %>%
  # filter(count > 2) %>%
  arrange(desc(count))
result


dd = diabetic_data %>%
filter(patient_nbr == '88785891')
dd
```

# Analysis

``` {r Descriptive Analysis}
# General Review

diabetic_data

#encoding
diabetic_data <- diabetic_data %>%
  mutate(readmitted_num = ifelse(readmitted == "NO", 0, ifelse(readmitted %in% c("<30", ">30"), 1, readmitted)))


# Number of medication changes: The dataset contains 23 features for 23 drugs (or combos) which indicate for each of these, whether a change in that medication was made or not during the current hospital stay of patient. Medication change for diabetics upon admission has been shown by previous research to be associated with lower readmission rates. We decided to count how many changes were made in total for each patient, and declared that a new feature. The reasoning here was to both simplify the model and possibly discover a relationship with number of changes regardless of which drug was changed.

keys <- c('metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'insulin', 'glyburide-metformin', 'tolazamide', 'metformin-pioglitazone', 'metformin-rosiglitazone', 'glimepiride-pioglitazone', 'glipizide-metformin', 'troglitazone', 'tolbutamide', 'acetohexamide')

df = diabetic_data

for (col in keys) {
  colname <- paste0(col, 'temp')
  df[[colname]] <- ifelse(df[[col]] %in% c('No', 'Steady'), 0, 1)
}
                
df$numchange <- 0

for (col in keys) {
  colname <- paste0(col, 'temp')
  df$numchange <- df$numchange + df[[colname]]
  df[[colname]] <- NULL
}

table(df$numchange)
df



df$change <- ifelse(df$change == 'Ch', 1, 0)
df$gender <- ifelse(df$gender == 'Male', 1, 0)
df$diabetesMed <- ifelse(df$diabetesMed == 'Yes', 1, 0)


for (col in keys) {
  df[[col]] <- ifelse(df[[col]] %in% c('No', 'Steady', 'Up', 'Down'), 1, 0)
}

df$A1Cresult <- ifelse(df$A1Cresult %in% c('>7', '>8'), 1,
                        ifelse(df$A1Cresult == 'Norm', 0,
                               ifelse(df$A1Cresult == 'None', -99, df$A1Cresult)))

df$max_glu_serum <- ifelse(df$max_glu_serum %in% c('>200', '>300'), 1,
                           ifelse(df$max_glu_serum == 'Norm', 0,
                                  ifelse(df$max_glu_serum == 'None', -99, df$max_glu_serum)))
df <- df %>%
mutate(age = ifelse(age == "[0-10)", 1,
             ifelse(age == "[10-20)", 2,
             ifelse(age == "[20-30)", 3,
             ifelse(age == "[30-40)", 4,
             ifelse(age == "[40-50)", 5,
             ifelse(age == "[50-60)", 6,
             ifelse(age == "[60-70)", 7,
             ifelse(age == "[70-80)", 8,
             ifelse(age == "[80-90)", 9,
             ifelse(age == "[90-100)", 10, NA
             )))))))))))

df <- df %>%
mutate(race = ifelse(race == "Other", 1,
             ifelse(race == "Asian", 2,
             ifelse(race == "Hispanic", 3,
             ifelse(race == "AfricanAmerican", 4,
             ifelse(race == "Caucasian", 5, NA
             ))))))

df <- df %>%
mutate(weight = ifelse(weight == "[0-25)", 1,
             ifelse(weight == "[25-50)", 2,
             ifelse(weight == "[50-75)", 3,
             ifelse(weight == "[75-100)", 4,
             ifelse(weight == "[100-125)", 5,
             ifelse(weight == "[125-150)", 6,
             ifelse(weight == "[150-175)", 7,
             ifelse(weight == "[175-200)", 8, NA
                    )))))))))




dummy_cols(gender)

# df$weight = as.integer(factor(df$weight, levels = c("[0-25)","[25-50)","[50-75)","[75-100)","[100-125)","[125-150)","[150-175)", "[175-200)", ">200")))


df

```

```{r}
unique(df$DIG_1)
```

```{r Descriptive Analysis}
# summary
diabetic_data$diag_1 <- as.character(diabetic_data$diag_1)
diabetic_data$diag_2 <- as.character(diabetic_data$diag_2)
diabetic_data$diag_3 <- as.character(diabetic_data$diag_3)
diabetic_data$readmitted_num <- as.numeric(diabetic_data$readmitted_num)

summarize_numeric(diabetic_data)
summarize_character(diabetic_data)

new_df$city <- factor(new_df$city, exclude = NULL)


#diabetic_data$diag_1 <- as.numeric(diabetic_data$diag_1)
#diabetic_data$diag_2 <- as.numeric(diabetic_data$diag_2)
#diabetic_data$diag_3 <- as.numeric(diabetic_data$diag_3)
```

```{r Descriptive Analysis}


```

```{r Descriptive Analysis}
# uni-variate analysis

# numeric attributes
num_var = select_if(diabetic_data, is.numeric)
num_var

# correlation coefficient
res <- cor(num_var)
round(res, 2)
corrplot(res, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)

# histogram
g1 = ggplot(num_var) + geom_histogram(aes(x = time_in_hospital), bins = 50)
g2 = ggplot(num_var) + geom_histogram(aes(x = num_lab_procedures), bins = 50)
g3 = ggplot(num_var) + geom_histogram(aes(x = num_procedures), bins = 50)
g4 = ggplot(num_var) + geom_histogram(aes(x = num_medications), bins = 50)
g5 = ggplot(num_var) + geom_histogram(aes(x = number_outpatient), bins = 50)
g6 = ggplot(num_var) + geom_histogram(aes(x = number_emergency),bins = 50)
g7 = ggplot(num_var) + geom_histogram(aes(x = number_inpatient),bins = 50)
g8 = ggplot(num_var) + geom_histogram(aes(x = number_diagnoses),bins = 50)
g6 = ggplot(num_var) + geom_histogram(aes(x = number_emergency),bins = 50)
g7 = ggplot(num_var) + geom_histogram(aes(x = number_inpatient),bins = 50)
g8 = ggplot(num_var) + geom_histogram(aes(x = number_diagnoses),bins = 50)

grid.arrange(g1, g2, g3, g4, g5, g6, g7, g8, nrow=3)

```
```{r Descriptive Analysis}
#character attributes
g10 = ggplot(char_var) + geom_bar(aes(x = race))
g11 = ggplot(char_var) + geom_bar(aes(x = gender))
g12 = ggplot(char_var) + geom_bar(aes(x = age))
g13 = ggplot(char_var) + geom_bar(aes(x = weight))
g14 = ggplot(char_var) + geom_bar(aes(x = payer_code))
g15 = ggplot(char_var) + geom_bar(aes(x = medical_specialty))
g16 = ggplot(char_var) + geom_bar(aes(x = diag_1))
g17 = ggplot(char_var) + geom_bar(aes(x = diag_2))
g18 = ggplot(char_var) + geom_bar(aes(x = diag_3))
g19 = ggplot(char_var) + geom_bar(aes(x = max_glu_serum))
g20 = ggplot(char_var) + geom_bar(aes(x = A1Cresult))
g21 = ggplot(char_var) + geom_bar(aes(x = metformin))
g22 = ggplot(char_var) + geom_bar(aes(x = repaglinide))
g23 = ggplot(char_var) + geom_bar(aes(x = nateglinide))
g24 = ggplot(char_var) + geom_bar(aes(x = chlorpropamide))
g25 = ggplot(char_var) + geom_bar(aes(x = glimepiride))
g26 = ggplot(char_var) + geom_bar(aes(x = acetohexamide))
g27 = ggplot(char_var) + geom_bar(aes(x = glipizide))
g28 = ggplot(char_var) + geom_bar(aes(x = glyburide))
g29 = ggplot(char_var) + geom_bar(aes(x = tolbutamide))
g30 = ggplot(char_var) + geom_bar(aes(x = pioglitazone))
g31 = ggplot(char_var) + geom_bar(aes(x = rosiglitazone))
g32 = ggplot(char_var) + geom_bar(aes(x = acarbose))
g33 = ggplot(char_var) + geom_bar(aes(x = miglitol))
g34 = ggplot(char_var) + geom_bar(aes(x = troglitazone))
g35 = ggplot(char_var) + geom_bar(aes(x = tolazamide))
g36 = ggplot(char_var) + geom_bar(aes(x = examide))
g37 = ggplot(char_var) + geom_bar(aes(x = citoglipton))
g38 = ggplot(char_var) + geom_bar(aes(x = insulin))
#g39 = ggplot(char_var) + geom_bar(aes(x = glyburide-metformin))
#g40 = ggplot(char_var) + geom_bar(aes(x = glipizide-metformin))
#g41 = ggplot(char_var) + geom_bar(aes(x = glimepiride-pioglitazone))
#g42 = ggplot(char_var) + geom_bar(aes(x = metformin-rosiglitazone))
#g43 = ggplot(char_var) + geom_bar(aes(x = metformin-pioglitazone))
g44 = ggplot(char_var) + geom_bar(aes(x = change))
g45 = ggplot(char_var) + geom_bar(aes(x = diabetesMed))
g46 = ggplot(char_var) + geom_bar(aes(x = readmitted))
g47 = ggplot(char_var) + geom_bar(aes(x = admission_type_description))
g48 = ggplot(char_var) + geom_bar(aes(x = discharge_disposition_description))
g49 = ggplot(char_var) + geom_bar(aes(x = admission_source_description))


#g10,g11,g12,g13,g14,g15,g16,g17,g18,g19,g20,g21,g22,g23,g24,g25,g26,g27,g28,g29,g30,g31,g32,g33,g34,g35,g36,g37,g38,g39,g40,g41,g42,g43,g44,g45,g46,g47,g48,g49
```

```{r}

df <- diabetic_data %>%
  mutate(readmitted_num = ifelse(readmitted == "NO", 0, ifelse(readmitted %in% c("<30", ">30"), 1, readmitted)))
df
```
```{r}
#g17 = ggplot(df) + geom_bar(aes(x = as.factor(Complain)))
#g20 = ggplot(df) + geom_bar(aes(x = as.factor(Response)))

grid.arrange(g10,g11,g12,g13)
             
#             g14,g15,g16,g17,g18,g19,g20,g21,g22,g23,g24,g25,g26,g27,g28,g29,g30,g31,g32,g33,g34,g35,g36,g37,g38,g44,g45,g46,g47,g48,g49, nrow = 20)


```

```{r Descriptive Analysis}
#sex
counts <- diabetic_data %>% filter(gender != "Unknown/Invalid") %>% group_by(gender) %>% summarise(n= n())
counts$percentage <- counts$n / sum(counts$n)

ggplot(counts, aes(x="", y=n, fill=gender)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) +
  geom_text(aes(label = paste0(round(percentage*100, 1), "%")), position = position_stack(vjust = 0.5)) +
  theme_void() +
  labs(title="Gender", fill="Gender")


#Age
counts <- diabetic_data %>% group_by(age) %>% summarise(n= n())
counts$percentage <- counts$n / sum(counts$n)

ggplot(counts, aes(x=age, y=n, fill=age)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = paste0(round(percentage*100, 1), "%")), vjust=-0.5) +
  labs(x="Age", y="Count", fill="Age", title="Bar Plot of Age")

#DRG
data_long <- diabetic_data %>% 
  select(DRG_1, DRG_2, DRG_3) %>% 
  gather(key = "DRG", value = "value") %>% 
  filter(!is.na(value))


counts <- data_long %>% group_by(value) %>% summarise(n = n(), .groups = "drop")
counts$percentage <- counts$n / sum(counts$n)
counts <- counts %>% arrange(desc(percentage)) %>% filter(percentage > 0.05) 

ggplot(counts, aes(x= reorder(value, percentage), y=n, fill=value)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  geom_text(aes(label = paste0(round(percentage*100, 1), "%")), vjust=-0.5) +
  labs(x="DRG", y="Count", fill="DRG", title="Bar Plot of DRG") + 
  theme(legend.position = "none") + 
  theme(axis.text.y = element_text(angle = 25, vjust = 0.5, hjust=1))

```

``` {r Diagnostic Analysis}
```

``` {r Predictive Analysis}

#partition <- createDataPartition(y = diabetic_data$readmitted, p = .70,list = FALSE)
#train <- diabetic_data[ partition,]
#test <- diabetic_data[-partition,]


#nnetModel <- nnet(formula = readmitted ~ age+number_diagnoses+DRG_1+DRG_2+DRG_3+A1Cresult,data = #train, size = 10, maxit = 100)




```

``` {r Prescriptive Analysis}
```